<a href="https://colab.research.google.com/github/iamhariharanvj/Learning-ML/blob/main/Regression_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regression Models

### Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importing the Dataset

In [ ]:
df = pd.read_csv('Data.csv')
df.head()

item id  date  No of items
0        1     1           20
1        1     2           22
2        1     3           24
3        1     4           25
4        1     5           28

In [ ]:
X = df.iloc[:,:-1].values # Enter the rows for your independent variable
y = df.iloc[:,-1].values   # Enter the rows for your dependent variable

In [ ]:
X[:5]

array([[1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 5]])

In [ ]:
y[:5]

array([20, 22, 24, 25, 28])

### Doing One Hot Encoding if necessary

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

columns = [0]
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),columns)] , remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
X

array([[ 1,  1],
       [ 1,  2],
       [ 1,  3],
       [ 1,  4],
       [ 1,  5],
       [ 1,  6],
       [ 1,  7],
       [ 1,  8],
       [ 1,  9],
       [ 1, 10],
       [ 1, 11],
       [ 1, 12],
       [ 1, 13],
       [ 1, 14],
       [ 1, 15],
       [ 1, 16],
       [ 1, 17],
       [ 1, 18],
       [ 1, 19],
       [ 1, 20],
       [ 1, 21],
       [ 1, 22],
       [ 1, 23],
       [ 1, 24],
       [ 1, 25]])

### Spliting the dataset into Training and Training Set

In [ ]:
test_size =0.1
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = test_size,random_state=0)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()

tfm_y_train = y_train.reshape(len(y_train),1)
tfm_y_test = y_test.reshape(len(y_test),1)

tfm_X_train = sc_X.fit_transform(X_train)
tfm_y_train = sc_y.fit_transform(tfm_y_train)
tfm_X_test = sc_X.transform(X_test)
tfm_y_test = sc_y.transform(tfm_y_test)

### Using Multiple Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_train,y_train)

LinearRegression()

In [ ]:
lin_ypred = lin_reg.predict(X_test)

### Using Polynomial Regression

In [ ]:
degree = 2
from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(degree = degree)
X_train_poly = pf.fit_transform(tfm_X_train)
poly_reg = LinearRegression()
poly_reg.fit(X_train_poly,tfm_y_train)

LinearRegression()

In [ ]:
X_test_poly = pf.fit_transform(tfm_X_test)
poly_y_pred = poly_reg.predict(X_test_poly)

### Using Support Vector Regression

In [ ]:
from sklearn.svm import SVR
svr = SVR(kernel='rbf')
svr.fit(tfm_X_train,tfm_y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [ ]:
svm_y_pred = sc_y.inverse_transform(svr.predict(tfm_X_test).reshape(-1,1))
svm_y_pred

array([[24.64489225],
       [23.24763295],
       [45.65370053]])

### Using Decision Tree Regression

In [ ]:
from sklearn.tree import DecisionTreeRegressor
tree = DecisionTreeRegressor()
tree.fit(X_train,y_train)

DecisionTreeRegressor()

In [ ]:
tree_y_pred = tree.predict(X_test)
tree_y_pred

array([28., 22., 44.])

### Using Random Forest Regression

In [ ]:
from sklearn.ensemble import RandomForestRegressor
forest = RandomForestRegressor(n_estimators = 20,random_state=0)
forest.fit(X_train,y_train)

RandomForestRegressor(n_estimators=20, random_state=0)

In [ ]:
forest_y_pred = forest.predict(X_test)
forest_y_pred

array([26.9 , 22.45, 45.2 ])

In [ ]:
from sklearn.metrics import r2_score
print('The score of Multiple Regression Model is ',r2_score(y_test,lin_ypred))
print('The score of Polynomial Regression Model is ',r2_score(y_test,poly_y_pred))
print('The score of Support Vector Regression Model is ',r2_score(y_test,svm_y_pred))
print('The score of Decison Tree Regression Model is ',r2_score(y_test,tree_y_pred))
print('The score of Random Forest Regression Model is ',r2_score(y_test,forest_y_pred))


The score of Multiple Regression Model is  0.9551854755171437
The score of Polynomial Regression Model is  -9.851405707964217
The score of Support Vector Regression Model is  0.9973690680045675
The score of Decison Tree Regression Model is  0.9449244060475162
The score of Random Forest Regression Model is  0.9784476241900648


In [ ]:
X_test


array([[ 1,  6],
       [ 1,  3],
       [ 1, 20]])

In [ ]:
print(sc_y.inverse_transform(svr.predict(sc_X.transform([[1,100]])).reshape(-1,1)))


[[34.37496843]]


In [ ]:
def linpredict(input):
  return lin_reg.predict(input)

In [ ]:
linpredict([[1,2]])

NameError: ignored